export const initialGradingResults = [
  {
    key: '1',
    student: 'Nguyễn Văn A',
    email: 'nva@gmail.com',
    test: 'Bộ đề thi thử Aptis Full Test #1',
    skill: 'Speaking',
    score: '38/50',
    duration: '11:15',
    date: '03/06/2026 10:24',
    status: 'graded',
  },
  {
    key: '2',
    student: 'Trần Thị B',
    email: 'ttb@gmail.com',
    test: 'Bộ đề thi thử Aptis Full Test #1',
    skill: 'Writing',
    score: '42/50',
    duration: '48:20',
    date: '02/06/2026 15:30',
    status: 'graded',
  },
  {
    key: '3',
    student: 'Lê Hoàng C',
    email: 'lhc@gmail.com',
    test: 'Bộ đề luyện riêng Writing Part 2',
    skill: 'Writing',
    score: '28/50',
    duration: '08:45',
    date: '02/06/2026 09:12',
    status: 'graded',
  },
  {
    key: '4',
    student: 'Hoàng Văn E',
    email: 'hve@gmail.com',
    test: 'Bộ đề thi thử Aptis Full Test #2',
    skill: 'Speaking',
    score: '32/50',
    duration: '12:00',
    date: '01/06/2026 14:15',
    status: 'graded',
  },
];
