export const initialStudents = [
  {
    key: '1',
    name: 'Nguyễn Văn A',
    email: 'nva@gmail.com',
    package: 'Premium',
    progress: 78,
    streak: 15,
    target: 'B2',
    registeredDate: '15/05/2026',
    active: true,
  },
  {
    key: '2',
    name: 'Trần Thị B',
    email: 'ttb@gmail.com',
    package: 'Pro',
    progress: 52,
    streak: 6,
    target: 'B1',
    registeredDate: '20/05/2026',
    active: true,
  },
  {
    key: '3',
    name: 'Lê Hoàng C',
    email: 'lhc@gmail.com',
    package: 'Miễn phí',
    progress: 25,
    streak: 0,
    target: 'A2',
    registeredDate: '25/05/2026',
    active: true,
  },
  {
    key: '4',
    name: 'Phạm Minh D',
    email: 'pmd@gmail.com',
    package: 'Premium',
    progress: 90,
    streak: 34,
    target: 'C',
    registeredDate: '01/05/2026',
    active: false,
  },
  {
    key: '5',
    name: 'Hoàng Văn E',
    email: 'hve@gmail.com',
    package: 'Pro',
    progress: 60,
    streak: 12,
    target: 'B2',
    registeredDate: '10/05/2026',
    active: true,
  },
];

export const initialPermissions = [
  { key: '1', action: 'Xem đề thi', superAdmin: true, admin: true, teacher: true, student: true },
  { key: '2', action: 'Làm đề thi', superAdmin: true, admin: true, teacher: true, student: true },
  { key: '3', action: 'Tạo đề thi mới', superAdmin: true, admin: true, teacher: true, student: false },
  { key: '4', action: 'Xoá đề thi', superAdmin: true, admin: true, teacher: false, student: false },
  { key: '5', action: 'Duyệt tài liệu', superAdmin: true, admin: true, teacher: false, student: false },
  { key: '6', action: 'Chấm điểm tự luận', superAdmin: true, admin: true, teacher: true, student: false },
  { key: '7', action: 'Quản trị hệ thống', superAdmin: true, admin: false, teacher: false, student: false },
];
