export const initialQuestions = [
  {
    key: '1',
    content: 'She would rather _______ at home than go to the party with us last night.',
    type: 'Grammar',
    difficulty: 'medium',
    tags: ['Prefer', 'Conditional'],
    useCount: 5,
    successRate: 72,
    status: 'active',
    updatedAt: '02/06/2026',
  },
  {
    key: '2',
    content: 'Under no circumstances _______ the door to strangers, she warned.',
    type: 'Grammar',
    difficulty: 'hard',
    tags: ['Inversion'],
    useCount: 12,
    successRate: 35,
    status: 'active',
    updatedAt: '01/06/2026',
  },
  {
    key: '3',
    content: 'Vocabulary Part 1: Synonyms matching set - Technology keywords.',
    type: 'Vocabulary',
    difficulty: 'easy',
    tags: ['Synonym', 'Tech'],
    useCount: 8,
    successRate: 84,
    status: 'active',
    updatedAt: '28/05/2026',
  },
  {
    key: '4',
    content: 'Reading Part 1: Family relations dialogue reading.',
    type: 'Reading',
    difficulty: 'easy',
    tags: ['Comprehension'],
    useCount: 3,
    successRate: 91,
    status: 'draft',
    updatedAt: '25/05/2026',
  },
  {
    key: '5',
    content: 'Listening Part 2: Airport delay announcement transcript.',
    type: 'Listening',
    difficulty: 'hard',
    tags: ['Announcement', 'Transport'],
    useCount: 10,
    successRate: 48,
    status: 'active',
    updatedAt: '20/05/2026',
  },
];
