export const initialQuestions = [
  {
    key: "1",
    content: "Part 1: Listening about a woman buying a dress at the shop.",
    type: "Listening",
    part: "part1",
    difficulty: "easy",
    tags: ["Aptis General", "Set 1"],
    useCount: 20,
    successRate: 85,
    status: "active",
    updatedAt: "15/06/2026",
  },
  {
    key: "2",
    content:
      "Part 2: Multiple speakers talking about their weekend activities.",
    type: "Listening",
    part: "part2",
    difficulty: "medium",
    tags: ["Aptis General", "Matching"],
    useCount: 15,
    successRate: 60,
    status: "active",
    updatedAt: "12/06/2026",
  },
  {
    key: "3",
    content: "Part 3: A man and a woman discussing a new office project.",
    type: "Listening",
    part: "part3",
    difficulty: "medium",
    tags: ["Opinion", "Workplace"],
    useCount: 8,
    successRate: 55,
    status: "active",
    updatedAt: "10/06/2026",
  },
  {
    key: "4",
    content: "Part 4: A long monologue about the history of the internet.",
    type: "Listening",
    part: "part4",
    difficulty: "hard",
    tags: ["Academic", "History"],
    useCount: 5,
    successRate: 40,
    status: "active",
    updatedAt: "05/06/2026",
  },
  {
    key: "5",
    content: 'Grammar: Sentence transformation using "unless".',
    type: "Grammar",
    part: "part1",
    difficulty: "medium",
    tags: ["Conditionals"],
    useCount: 30,
    successRate: 75,
    status: "active",
    updatedAt: "01/06/2026",
  },
  {
    key: "6",
    content: "Vocabulary: Matching synonyms for environmental terms.",
    type: "Grammar",
    part: "part2",
    difficulty: "easy",
    tags: ["Environment"],
    useCount: 45,
    successRate: 90,
    status: "active",
    updatedAt: "28/05/2026",
  },
];
