export const initialMaterials = [
  {
    key: '1',
    name: 'Tài liệu hướng dẫn viết thư Aptis Writing Part 4',
    skill: 'Writing',
    format: 'pdf',
    uploader: 'Giáo viên Phạm H.',
    date: '02/06/2026',
    downloads: 320,
    size: '2.4 MB',
    status: 'approved',
    description: 'Tài liệu tổng hợp các mẫu thư hồi âm thân mật và trang trọng trong bài thi Aptis Writing.',
  },
  {
    key: '2',
    name: 'Tổng hợp 50 cụm từ vựng Speaking miêu tả tranh phổ biến',
    skill: 'Speaking',
    format: 'word',
    uploader: 'Admin',
    date: '01/06/2026',
    downloads: 850,
    size: '1.1 MB',
    status: 'approved',
    description: '50 mẫu câu miêu tả phong cảnh, người, động vật để ghi điểm tối đa phần mô tả hình ảnh.',
  },
  {
    key: '3',
    name: 'Audio luyện nghe Part 2: Điền thông tin vào form',
    skill: 'Listening',
    format: 'audio',
    uploader: 'Giáo viên Trần K.',
    date: '28/05/2026',
    downloads: 140,
    size: '8.5 MB',
    status: 'pending',
    description: 'File âm thanh giọng Anh-Anh chuyên sâu luyện tập điền từ khoá vào form đăng ký du lịch.',
  },
  {
    key: '4',
    name: 'Bài giảng Video hướng dẫn mẹo làm bài Reading Part 3',
    skill: 'Reading',
    format: 'video',
    uploader: 'Giáo viên Hoàng V.',
    date: '25/05/2026',
    downloads: 210,
    size: '42 MB',
    status: 'approved',
    description: 'Xem chi tiết hướng dẫn phương pháp skimming & scanning câu hỏi đọc hiểu đoạn văn ngắn.',
  },
];
